### ISSUE TITLE
Agree on a wake word of at least 3 syllables (like "Project Cue"...)

### ISSUE THREAD

**Issue by julienw** [fxbox/calendar#47]

**Comment by julienw** [comment]
https://public.etherpad-mozilla.org/p/project-cue-wakeword

**Comment by gmarty** [comment]
In https://github.com/fxbox/calendar/pull/62, @samgiles introduced "Make a note" as the wake word.
I personnally like it.

**Comment by julienw** [comment]
why not :)

**Comment by JohanLorenzo** [comment]
That'll be very accurate once we have to-do lists 😄 This set of word sounds great to me

**Comment by gmarty** [comment]
Let's close this issue for now as we all agreed on "Make a note".
